carrinho/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.detalhes_do_carrinho, name='detalhes_do_carrinho'),
    url(r'^adicionar/(?P<id_produto>\d+)/$', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    url(r'^remover/(?P<id_produto>\d+)/$', views.remover_do_carrinho, name='remover_do_carrinho'),
]

loja/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^carrinho/', include('carrinho.urls', namespace='carrinho')),  # Esta entrada deve aparecer antes da última
    # pois é mais restritiva.
    url(r'^', include('vendas.urls', namespace='vendas')),
]

carrinho/models.py
from django.db import models

# Create your models here.

carrinho/forms.py
from django import forms

OPCOES_DE_QUANTIDADE_PARA_O_PRODUTO = [(i, str(i)) for i in range(1, 21)]

class FormularioParaAdicaoDeProdutosAoCarrinho(forms.Form):
    quantidade = forms.TypedChoiceField(label="Quantidade ",
                                        choices=OPCOES_DE_QUANTIDADE_PARA_O_PRODUTO,
                                        coerce=int,
                                        widget=forms.Select(attrs={'class': 'form-control input-sm',
                                                                   'style': 'margin-left: 6px; margin-right: 6px; max-width: 60px; text-center'}))

    atualizar = forms.BooleanField(required=False,             # O default é required=True
                                   initial=False,
                                   widget=forms.HiddenInput)

carrinho/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .carrinho import Carrinho
from vendas.models import Produto
from .forms import FormularioParaAdicaoDeProdutosAoCarrinho

@require_POST            # Para permitir que esta view só possa ser executada via POST pois ela modifica dados
def adicionar_ao_carrinho(request, id_produto):   # Essa view recebe o id do produto
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    print(produto.preco)
    # a view valida o formulário
    form = FormularioParaAdicaoDeProdutosAoCarrinho(request.POST)
    if form.is_valid():  # executa as rotinas de validação para todos os campos do formulário. Quando este método
                         # é chamado, se todos os campos tiverem dados válidos ele irá:
                         # - retornar True
                         # - colocar os dados do form no atributo cleaned_data do formulário
        cd = form.cleaned_data

        # Se o formulário for válido, adicionamos ou atualizamos o
        # produto no carrinho na qtd informada.
        carrinho.adicionar(produto=produto,
                         quantidade=cd['quantidade'],
                         atualiza_quantidade=cd['atualizar'])
    # A view redireciona para o detalhes_do_carrinho URL que irá exibir o conteúdo do carrinho.
    return redirect('carrinho:detalhes_do_carrinho') # Este redirect fará com que a requisição seja redirecionada
                                                     # para http://127.0.0.1:8000/carrinho


def detalhes_do_carrinho(request):
    carrinho = Carrinho(request)

    lista = carrinho.get_lista_de_itens_de_carrinho()

    for item in lista:
        item['atualizar_quantidade_form'] = FormularioParaAdicaoDeProdutosAoCarrinho(
            initial={'quantidade': item['quantidade'], 'atualizar': True})

    return render(request, 'carrinho/exibe.html', {'carrinho': carrinho, 'lista': lista})

def remover_do_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    carrinho.remover(produto)
    return redirect('carrinho:detalhes_do_carrinho')

carrinho/templates/carrinho/exibe.html
{% extends "vendas/base.html" %}

{% load static %}

{% block titulo %}
    Seu carrinho de compras
{% endblock %}

{% block conteudo %}
    <div class="container">
        <div class="row">
            <h3>Seu carrinho de compras</h3>
            <table class="table table-striped table-bordered table-responsive">
                <thead>
                <tr>
                    <th class="text-center">Imagem</th>
                    <th class="text-center">Produto</th>
                    <th class="text-center fit">Quantidade</th>
                    <th class="text-center">Preço Unitário</th>
                    <th class="text-center">Preço Total</th>
                </tr>
                </thead>
                <tbody>
                {% for item in lista %}
                    <tr>
                        <td>
                            <a href="{{ item.produto.get_absolute_path }}">
                                <img style="max-height: 90px" class="img-rounded img-responsive center-block"
                                     src="{% static '/vendas/imagens/' %}{{ item.produto.imagem }}">
                            </a>
                        </td>
                        <td>{{ item.produto.nome }}</td>
                        <td class="fit">
                            <form class="form-inline text-center" method="post"
                                  action="{% url 'carrinho:adicionar_ao_carrinho' item.id %}">
                                {{ item.atualizar_quantidade_form.quantidade }}
                                {{ item.atualizar_quantidade_form.atualizar }}
                                <input class="btn btn-primary btn-sm" type="submit" value="Atualizar">
                                <a class="btn btn-danger btn-sm"
                                   href="{% url 'carrinho:remover_do_carrinho' item.id %}">Remover</a>
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="text-right">R$ {{ item.preco }}</td>
                        <td class="text-right">R$ {{ item.preco_total }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td><b>Total do Pedido</b></td>
                    <td colspan="3"></td>
                    <td class="text-right">R$ {{ carrinho.get_preco_total }}</td>
                </tr>
                </tbody>
            </table>
            <p class="text-right">
                <a href="/" class="btn btn-primary">Continuar comprando</a>
            </p>
        </div>
    </div>
{% endblock %}